version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: nuget restore

build:
  project: RedStar.Amounts.sln
  verbosity: minimal

artifacts:
 - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: /VAOa0UONsIRjh/Ym5y62ZH38qGkIjCeFjML8wldfRjkfN4NY68/D7SvairY6f3X
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
