version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: nuget restore

build:
  project: RedStar.Amounts.sln
  verbosity: minimal

test:
  assemblies:
    only:
      - '**\*.Tests.dll'

artifacts:
 - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: +mnhqvOwBfjGVDSyHH3v/V6/F8HKppciwMNahegBzPSENZ29HXDtX1Hs55JmKrYM
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
