version: 1.0.{build}
image: Visual Studio 2022
configuration: Release

before_build:
- cmd: nuget restore

build:
  project: RedStar.Amounts.sln
  verbosity: minimal

artifacts:
 - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: gAkkFfgn8r8wXSYJOOPA2EeIQW0LiFuIt/YnX/VvC+OM8hdduK2braoaYxrwBPYm
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
